name: home_module
description: Modulo responsável pela página home.
publish_to: 'none'
version: 0.0.1

environment:
  sdk: ">=3.2.4 <4.0.0"
  flutter: ">=3.16.7"

dependencies:
  flutter:
    sdk: flutter
  dependencies_module:
    path: ../dependencies_module

dev_dependencies:

  flutter_lints: ^2.0.0

flutter:
