name: remessas_module
description: Modulo para gerenciamento das Remessas.
publish_to: 'none'
version: 0.0.1

environment:
  sdk: ">=3.2.4 <4.0.0"
  flutter: ">=3.16.7"

dependencies:
  flutter:
    sdk: flutter
  dependencies_module:
    path: ../dependencies_module
  syncfusion_flutter_pdf: ^20.3.50
  printing: ^5.9.3
  archive: ^3.3.2

dev_dependencies:

  flutter_lints: ^2.0.0

flutter:
