name: dependencies_module
description: Modulo responsável pelo gerenciamento das dependencias.
publish_to: 'none'
version: 0.0.1

environment:
  sdk: ">=3.2.4 <4.0.0"
  flutter: ">=3.16.7"

dependencies:
  flutter:
    sdk: flutter

  # Modulos
  design_system_module:
    path: ../design_system_module
  core_module:
    path: ../core_module
  splash_module:
    path: ../splash_module
  # login_module:
  #   path: ../login_module
  home_module:
    path: ../home_module
  upload_remessa_module:
    path: ../upload_remessa_module
  remessas_module:
    path: ../remessas_module

  # Package
  upload_arquivo_html_package:
    path: ../../packages/upload_arquivo_html_package

  # Externos
  return_success_or_error: ^0.4.2
  get: ^4.6.6
  get_storage: ^2.0.3
  intl: ^0.17.0
  font_awesome_flutter: ^10.2.1
  csv: ^5.0.1
  uuid: ^3.0.6
  percent_indicator: ^4.2.2
  file_picker: ^5.2.2
  path: ^1.8.2
  path_provider: ^2.0.11
  firedart: ^0.9.0+1
  objectbox: ^1.6.2
  objectbox_flutter_libs: any

dev_dependencies:
  flutter_lints: ^2.0.0

flutter:
