name: design_system_module
description: Modulo responsável pelo gerenciamento do designer.
publish_to: 'none'
version: 0.0.3
homepage:

environment:
  sdk: '>=2.18.4 <3.0.0'
  flutter: ">=3.3.8"

dependencies:
  flutter:
    sdk: flutter
  dependencies_module:
    path: ../dependencies_module
  pdf: ^3.8.3
  printing: ^5.9.3
  flutter_excel: ^1.0.1
  percent_indicator: ^4.2.2

dev_dependencies:

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
