name: core_module
description: Modulo responsável pelo gerenciamento geral da aplicação.
publish_to: 'none'
version: 0.0.1

environment:
  sdk: ">=3.2.4 <4.0.0"
  flutter: ">=3.16.7"

dependencies:
  flutter:
    sdk: flutter
  dependencies_module:
    path: ../dependencies_module
  objectbox: ^1.6.2
  objectbox_flutter_libs: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.0.0
  objectbox_generator: any

objectbox:
  output_dir:
    lib: src\services\service\database\db

flutter:
